spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:shinyano@localhost:8761/eureka
zuul:
  routes:
    microservice-provider-user: /api/user/**